---

# Cancels duplicate github actions when superseded

name: Cancelling Duplicates
on:
  workflow_run:
    workflows:
      - 'Pull Request'
      - 'Deploy'
      - 'Linting (Non-Image)'
    types: ['requested']

jobs:
  cancel-duplicate-workflow-runs:
    name: "Cancel duplicate workflow runs"
    runs-on: ubuntu-latest
    steps:
      - uses: potiuk/cancel-workflow-runs@master
        name: "Cancel duplicate workflow runs"
        with:
          cancelMode: allDuplicates
          token: ${{ secrets.NTT_PAT }}
          sourceRunId: ${{ github.event.workflow_run.id }}
